"""add objective summary outcome columns

Revision ID: 64314a26bad7
Revises: 92c6f0f8d999
Create Date: 2026-07-11 13:16:19.391402
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '64314a26bad7'
down_revision = '92c6f0f8d999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('objective', sa.String(length=255), nullable=True))
    op.add_column('interactions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('outcome', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'outcome')
    op.drop_column('interactions', 'summary')
    op.drop_column('interactions', 'objective')
    # ### end Alembic commands ###

