"""create interactions table

Revision ID: 92c6f0f8d999
Revises: 20260711_01
Create Date: 2026-07-11 13:13:25.443766
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '92c6f0f8d999'
down_revision = '20260711_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hcp_id', sa.UUID(), nullable=False),
    sa.Column('visit_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('products_discussed', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hcp_id'], ['healthcare_professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_date'), 'interactions', ['date'], unique=False)
    op.create_index(op.f('ix_interactions_hcp_id'), 'interactions', ['hcp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_hcp_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_date'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###

